extern char *first_unused_character;
extern char *first_character_of_the_lexeme;
extern int symbol;
extern int errortype;
extern int reloctype;
extern int evalswitch;
extern valtype number;
extern char name[MAXLINLEN];
extern char *original_name;
extern char cline[MAXLINLEN];
extern char readinbuff[MAXLINLEN];
extern char listline[MAXLINLEN + ADDRESS +3*VALUESS +1];
extern int fly_over_the_lines;
extern char *include_directory;
extern int  buffpos;
extern int  incdepth;
extern FILE *inputfile[MAXINCNEST];
extern struct macro *macroot[PRIME];
extern struct macro *maclast[PRIME];
extern int macqueindx;
extern struct symbol *hashtable[ PRIME ];
extern int pass;
extern struct macrostack *mslast;
extern unsigned valtype *dollar;
extern unsigned valtype *symline;
extern unsigned valtype *symtline;
extern unsigned valtype *sympass;
extern unsigned long dollmin,dollmax;
extern int ondeep,offdeep;
extern int mac_nest_deep;
extern struct loopstack *loopstacklast;
extern struct exeline *cmline;
extern struct symbol *dummy_set;
extern int phaseoffset;
extern int nrprvl;
extern int nrerrors,nrwarnings;
extern char *code;
extern int casesen;
extern FILE *listfile;
extern int listswitch;
extern int maclist;
extern int tskswitch;
extern int headswitch;
extern int glistswitch;
extern int ilistswitch;
extern int mlistswitch;
extern int Nrofthesets;
extern FILE *libfile;
extern int setnumbering;
extern char *outfilnam;
extern int first_flag;
extern struct symbol *setptr000,*setptr001,*setptr002,*setptr003;
extern struct errstack *erroot;
extern int asciiradix;
extern int lmori;
extern int dwflag,ddflag;
extern int macarg;
extern int macnum;
extern int macextnum;
extern int stdoutsw;
extern struct usrs *usrstk[USRSTKSIZ];
extern char usrsf[USRSTKSIZ];
extern char linkbuff[2000];
extern int linkbuffpos;
extern int linkbloctype;
extern FILE *linkfp;
extern int nexternal;
extern int objgen;
extern struct reloc rebuff[256];
extern int rebuffpos;
extern int codepos;
extern valtype fadblk;
extern char __tolower__[0x100];
extern char char_code[];
